---

- name: Ensure kibana is installed
  win_chocolatey:
    name: kibana --allow-empty-checksums
    version: "{{ kibana_version }}"
    # Workaround: broken chocolatey package with wrong checksums
    # ignore_checksums: true
    # allow_empty_checksums: true
    state: present
  # TODO: Turn on for new ansible 2.2
  # notify: kibana restart

- name: Ensure configuration kibana.yml is generated
  win_template:
    src: kibana.yml.j2
    dest: "{{kibana_home}}/config/kibana.yml"
  notify: kibana restart

- name: Ensure kibana service is started
  win_service: name=kibana-service start_mode=auto state=started
  notify: kibana restart

- name: Ensure kiban port {{ kibana_server_port }} is opened
  win_firewall_rule:
    name: kibana
    enable: yes
    state: present
    # Workaround: ansible issue with default profile
    profile: "Domain,Private,Public"
    localport: "{{ kibana_server_port }}"
    action: allow
    direction: In
    protocol: TCP
  when: "{{ kibana_server_host != '127.0.0.1' }}"
