---

- name: Ensure kibana is installed
  win_chocolatey:
    name: kibana -y --allow-empty-checksums
    version: "{{ kibana_version }}"
    state: present

- name: Ensure configuration kibana.yml is generated
  win_template:
    src: kibana.yml.j2
    dest: "{{kibana_home}}/config/kibana.yml"
  notify: kibana restart

- name: Ensure kibana service is started
  win_service: name=kibana-service start_mode=auto state=started
  notify: kibana restart

# TODO: default host is 127.0.0.1 in this case no need to open port
# Think on reasonable compatible defaults
- name: Ensure kiban port {{ kibana_server_port }} is opened
  win_firewall_rule:
    name: kibana
    enable: yes
    state: present
    localport: "{{ kibana_server_port }}"
    action: allow
    direction: In
    protocol: TCP
